appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: WZuunKJQx3X3FQ84Kkzjmtwo9lt3Fa+szq2KZMIYDfWnLA6rlHeaXAKZHjoO3lwHVHlniiwTZo8BUGbV6PwZrChAJfL0k8hHxGYD3WvaBTctghkGCCqN+dAJt13Bfmv/gSCjtDnuqd96YViKbFJ46nk960qX4GQB19WqZBTDNYG6AE/0cQcQZ4i4xGWkgVWXYBjJjvNooc07wW0Jx3nArcLhe5QNRabc75YIksWvpo3OnTQFtg8dnqbaWXDVfN8qHsqWuvT0hUH8zZ8DT6lCnpebTkQ4HfXYgvGUGy+o/InOGFwh293/g9mg5Q5WBNbgJxTKz4BwEJX++MHDS90Ow79rKPNvsSM/zco/YcyRcahjjv7CvCXMZmukZG4Wce9oKmRL/QFuWIxMq4F8qzQbBP+uzcItGfMXzQVsD+Tv3ZcuFdKgdszc1TlxCqOyHU0JhjkvWYHkxUsUqFSOOW6o90j4W1fSs/1CBSok3cNMRpuYoYSRMoMICYvajoFcRdTTt5QzWPYq8noQ0Lp/ftMKOAIEMTzaU71xRM3EeEjLYc6Ei3+L4B6mil0/fzzuKdy2piJFOrT0QIeoGeckj5yo2U2PqR98K89NsMFXm4Dsn7w8vtAWwqAFKrJBECCfcN4SXN8s0fYCk0K/UgQgn5jbFI/gpD2ZlFBcqCrS4RMGXMs=
conda_forge_output_validation: true
